apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: setu-rp-run
spec:
  pipelineRef:
    name: setu-rp-pipeline
  params:
    - name: repo-owner
      value: "openshift"
    - name: repo-name
      value: "hypershift"
    - name: db-path
      value: "/workspace/data/hypershift.db"
  workspaces:
    - name: shared-data
      persistentVolumeClaim:
        claimName: setu-rp-data
